### ISSUE TITLE
exercism submit doesn't update exercise

### ISSUE THREAD

**Issue by dwrz** [exercism/support#7]
`exercism submit` reports a successful submission, but the exercise on the web isn't updated.

I've checked the URL from `Firefox` and `Chromium` and made sure to clear the cache in both browsers.

```
exercism submit src/beer_song.h src/beer_song.c

    Your solution has been submitted successfully.
    View it at:

    https://exercism.io/my/solutions/4bef136f08184be7946ecbbcf0af40f1
```

Output of `exercism troubleshoot`:
```
exercism troubleshoot                                                                                                                        222102

Troubleshooting Information
===========================

Version
----------------
Current: 3.0.11
Latest:  3.0.11


Operating System
----------------
OS:           linux
Architecture: amd64


Configuration
----------------
Home:      /home/dwrz
Workspace: /home/dwrz/path/to/exercism/workspace
Config:    /home/dwrz/.config/exercism
API key:   ************************************

API Reachability
----------------

GitHub:
    * https://api.github.com
    * [connected]
    * 26.870463ms

Exercism:
    * https://api.exercism.io/v1/ping
    * [connected]
    * 424.971568ms


If you are having trouble please file a GitHub issue at
https://github.com/exercism/exercism.io/issues and include
this information.
```

**Comment by sshine** [comment]
Hi @dwrz. Did you eventually progress beyond this error report?

**Comment by dwrz** [comment]
The mentor was able to look at the updated solution I hosted in my own Github repo, then approved my outdated solution. So, personally I was able to move on, but not because the bug was resolved (at least at the time).

**Comment by sshine** [comment]
OK. Is `Workspace: /home/dwrz/path/to/exercism/workspace` actual output, or did you modify this?

Does the problem persist for other exercises than Beer Song?
